version: '3.8'

services:
  baby-worksheet:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - baby_data:/app/data
    user: "1001:1001"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
      - DEBUG_MODE=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  baby_data:
    driver: local