version: '3.8'

services:
  baby-worksheet:
    image: ghcr.io/your-username/baby-worksheet:latest
    ports:
      - "3001:3001"
    volumes:
      - baby_data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  baby_data:
    driver: local